---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'RIOS with AWS Batch using CloudFormation'
Parameters:
  ServiceName:
    Type: String
    Default: rios
  AZ1:
    Type: String
    Default: ap-southeast-2a
  AZ2:
    Type: String
    Default: ap-southeast-2b
  AZ3:
    Type: String
    Default: ap-southeast-2c
  VCPUS:
    Type: Number
    Default: 1
  MaxMemory:
    Type: Number
    Default: 4000
  MaxJobs:
    Type: Number
    Default: 32
    
Resources:
  BatchVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'false'
  BatchSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: BatchVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: !Ref AZ1
  BatchSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: BatchVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Ref AZ2
  BatchSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: BatchVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Ref AZ3
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['', [!Ref ServiceName, "Security Group"]]
      GroupDescription: "Security Group for RIOS VPC"
      VpcId: !Ref BatchVPC
    
  BatchRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join ['', [!Ref ServiceName, "ecr"]]
          
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
                {
                    "rulePriority": 1,
                    "description": "Expire images older than 1 day",
                    "selection": {
                        "tagStatus": "untagged",
                        "countType": "sinceImagePushed",
                        "countUnit": "days",
                        "countNumber": 1
                    },
                    "action": {
                        "type": "expire"
                    }
                }
            ]
          }
        
  BatchInQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ['', [!Ref ServiceName, InQueue]]

  BatchOutQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ['', [!Ref ServiceName, OutQueue]]
      
  BatchBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [!Ref ServiceName, bucket]]
      
  AccessS3ManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for allowing jobs to access S3 Bucket
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: 's3:*Object'
          Resource:
            - !GetAtt BatchBucket.Arn
            
  AccessQueuesS3ManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for allowing jobs to our SQS Queues
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: 
            - 'sqs:SendMessage'
            - 'sqs:ReceiveMessage'
            - 'sqs:DeleteMessage'
          Resource:
            - !GetAtt BatchInQueue.Arn
            - !GetAtt BatchOutQueue.Arn
      
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: batch.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - Ref: EcsInstanceRole
  EcsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
      - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      - !Ref AccessS3ManagedPolicy
      - !Ref AccessQueuesS3ManagedPolicy
  BatchProcessingJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: !Join ['', [!Ref ServiceName, "JobDefinition"]]
      ContainerProperties:
        Image: !Join ['', [!GetAtt BatchRepository.RepositoryUri, ":latest"]]
        Vcpus: !Ref VCPUS
        Memory: !Ref MaxMemory
        Environment:
          - Name: "RIOSBucket"
            Value: !Ref BatchBucket
          - Name: "RIOSInQueue"
            Value: !Ref BatchInQueue
          - Name: "RIOSOutQueue"
            Value: !Ref BatchOutQueue
  BatchProcessingJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Join ['', [!Ref ServiceName, "JobQueue"]]
      Priority: 1
      ComputeEnvironmentOrder:
      - Order: 1
        ComputeEnvironment:
          Ref: ComputeEnvironment
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        DesiredvCpus: 0
        MaxvCpus: !Ref MaxJobs
        InstanceTypes:
        - optimal
        Subnets:
        - !Ref BatchSubnet1
        - !Ref BatchSubnet2
        - !Ref BatchSubnet3
        SecurityGroupIds:
        - !Ref BatchSecurityGroup
        InstanceRole:
          Ref: IamInstanceProfile
      ServiceRole:
        Ref: BatchServiceRole
     
Outputs:
  VPC:
    Value:
      Ref: BatchVPC
  ComputeEnvironmentArn:
    Value:
      Ref: ComputeEnvironment
  BatchProcessingJobQueueArn:
    Value:
      Ref: BatchProcessingJobQueue
  BatchProcessingJobQueueName:
    Value: !Join ['', [!Ref ServiceName, "JobQueue"]]
  BatchProcessingJobDefinitionArn:
    Value:
      Ref: BatchProcessingJobDefinition
  BatchProcessingJobDefinitionName:
    Value: !Join ['', [!Ref ServiceName, "JobDefinition"]]
  BatchECR:
    Value: !GetAtt BatchRepository.RepositoryUri
  BatchInQueue:
    Value:
      Ref: BatchInQueue
  BatchOutQueue:
    Value:
      Ref: BatchOutQueue
  BatchBucket:
    Value:
      Ref: BatchBucket
