
FROM rios

RUN pip install pystac-client

RUN mkdir /usr/local/data
COPY sentinel_2_index_centroid.gpkg /usr/local/data

COPY medianConcTest.py /usr/local/bin

WORKDIR /usr/local/data
ENTRYPOINT ["/usr/bin/python3", "/usr/local/bin/medianConcTest.py"]

